export const AUTHORIZATION_ACTIONS = [
  "workspace.view",
  "workspace.members.read",
  "workspace.members.manage",
  "workspace.invitations.read",
  "workspace.invitations.manage",
  "workspace.integrations.github.read",
  "workspace.integrations.github.manage",
  "project.view",
  "project.create",
  "project.update",
  "project.archive",
  "project.restore",
  "project.delete",
  "project.settings.read",
  "project.settings.update",
  "project.repository_binding.read",
  "project.repository_binding.write",
  "project.local_path.provision",
  "project.local_path.sync",
  "project.files.read",
  "project.files.write",
  "project.git.read",
  "project.git.write",
  "project.git.subscribe",
  "project.tasks.read",
  "project.tasks.create",
  "task.view",
  "task.update",
  "task.cancel",
  "task.resume",
  "task.delete",
  "task.events.read",
  "task.subscribe",
  "orchestration.view",
  "orchestration.create",
  "orchestration.task.create",
] as const

export type AuthorizationAction = (typeof AUTHORIZATION_ACTIONS)[number]
