/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WorkspacesRouteImport } from "./routes/workspaces"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as BrandRouteImport } from "./routes/brand"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WorkspacesIndexRouteImport } from "./routes/workspaces/index"
import { Route as WorkspacesWorkspaceIdRouteRouteImport } from "./routes/workspaces/$workspaceId/route"
import { Route as WorkspacesWorkspaceIdIndexRouteImport } from "./routes/workspaces/$workspaceId/index"
import { Route as GithubAppCallbackRouteImport } from "./routes/github/app/callback"
import { Route as WorkspacesWorkspaceIdProjectsProjectIdRouteRouteImport } from "./routes/workspaces/$workspaceId/projects/$projectId/route"
import { Route as WorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport } from "./routes/workspaces/$workspaceId/projects/$projectId/index"
import { Route as WorkspacesWorkspaceIdProjectsProjectIdSettingsRouteImport } from "./routes/workspaces/$workspaceId/projects/$projectId/settings"
import { Route as WorkspacesWorkspaceIdProjectsProjectIdScheduleRouteImport } from "./routes/workspaces/$workspaceId/projects/$projectId/schedule"
import { Route as WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRouteImport } from "./routes/workspaces/$workspaceId/projects/$projectId/schedule_.$orchestrationId"

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: "/workspaces",
  path: "/workspaces",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: "/brand",
  path: "/brand",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => WorkspacesRoute,
} as any)
const WorkspacesWorkspaceIdRouteRoute =
  WorkspacesWorkspaceIdRouteRouteImport.update({
    id: "/$workspaceId",
    path: "/$workspaceId",
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceIdIndexRoute =
  WorkspacesWorkspaceIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => WorkspacesWorkspaceIdRouteRoute,
  } as any)
const GithubAppCallbackRoute = GithubAppCallbackRouteImport.update({
  id: "/github/app/callback",
  path: "/github/app/callback",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdProjectsProjectIdRouteRoute =
  WorkspacesWorkspaceIdProjectsProjectIdRouteRouteImport.update({
    id: "/projects/$projectId",
    path: "/projects/$projectId",
    getParentRoute: () => WorkspacesWorkspaceIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdProjectsProjectIdIndexRoute =
  WorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => WorkspacesWorkspaceIdProjectsProjectIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdProjectsProjectIdSettingsRoute =
  WorkspacesWorkspaceIdProjectsProjectIdSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => WorkspacesWorkspaceIdProjectsProjectIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdProjectsProjectIdScheduleRoute =
  WorkspacesWorkspaceIdProjectsProjectIdScheduleRouteImport.update({
    id: "/schedule",
    path: "/schedule",
    getParentRoute: () => WorkspacesWorkspaceIdProjectsProjectIdRouteRoute,
  } as any)
const WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRoute =
  WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRouteImport.update(
    {
      id: "/schedule_/$orchestrationId",
      path: "/schedule/$orchestrationId",
      getParentRoute: () => WorkspacesWorkspaceIdProjectsProjectIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/brand": typeof BrandRoute
  "/login": typeof LoginRoute
  "/workspaces": typeof WorkspacesRouteWithChildren
  "/workspaces/$workspaceId": typeof WorkspacesWorkspaceIdRouteRouteWithChildren
  "/workspaces/": typeof WorkspacesIndexRoute
  "/github/app/callback": typeof GithubAppCallbackRoute
  "/workspaces/$workspaceId/": typeof WorkspacesWorkspaceIdIndexRoute
  "/workspaces/$workspaceId/projects/$projectId": typeof WorkspacesWorkspaceIdProjectsProjectIdRouteRouteWithChildren
  "/workspaces/$workspaceId/projects/$projectId/schedule": typeof WorkspacesWorkspaceIdProjectsProjectIdScheduleRoute
  "/workspaces/$workspaceId/projects/$projectId/settings": typeof WorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  "/workspaces/$workspaceId/projects/$projectId/": typeof WorkspacesWorkspaceIdProjectsProjectIdIndexRoute
  "/workspaces/$workspaceId/projects/$projectId/schedule/$orchestrationId": typeof WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/brand": typeof BrandRoute
  "/login": typeof LoginRoute
  "/workspaces": typeof WorkspacesIndexRoute
  "/github/app/callback": typeof GithubAppCallbackRoute
  "/workspaces/$workspaceId": typeof WorkspacesWorkspaceIdIndexRoute
  "/workspaces/$workspaceId/projects/$projectId/schedule": typeof WorkspacesWorkspaceIdProjectsProjectIdScheduleRoute
  "/workspaces/$workspaceId/projects/$projectId/settings": typeof WorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  "/workspaces/$workspaceId/projects/$projectId": typeof WorkspacesWorkspaceIdProjectsProjectIdIndexRoute
  "/workspaces/$workspaceId/projects/$projectId/schedule/$orchestrationId": typeof WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/brand": typeof BrandRoute
  "/login": typeof LoginRoute
  "/workspaces": typeof WorkspacesRouteWithChildren
  "/workspaces/$workspaceId": typeof WorkspacesWorkspaceIdRouteRouteWithChildren
  "/workspaces/": typeof WorkspacesIndexRoute
  "/github/app/callback": typeof GithubAppCallbackRoute
  "/workspaces/$workspaceId/": typeof WorkspacesWorkspaceIdIndexRoute
  "/workspaces/$workspaceId/projects/$projectId": typeof WorkspacesWorkspaceIdProjectsProjectIdRouteRouteWithChildren
  "/workspaces/$workspaceId/projects/$projectId/schedule": typeof WorkspacesWorkspaceIdProjectsProjectIdScheduleRoute
  "/workspaces/$workspaceId/projects/$projectId/settings": typeof WorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  "/workspaces/$workspaceId/projects/$projectId/": typeof WorkspacesWorkspaceIdProjectsProjectIdIndexRoute
  "/workspaces/$workspaceId/projects/$projectId/schedule_/$orchestrationId": typeof WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/brand"
    | "/login"
    | "/workspaces"
    | "/workspaces/$workspaceId"
    | "/workspaces/"
    | "/github/app/callback"
    | "/workspaces/$workspaceId/"
    | "/workspaces/$workspaceId/projects/$projectId"
    | "/workspaces/$workspaceId/projects/$projectId/schedule"
    | "/workspaces/$workspaceId/projects/$projectId/settings"
    | "/workspaces/$workspaceId/projects/$projectId/"
    | "/workspaces/$workspaceId/projects/$projectId/schedule/$orchestrationId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/brand"
    | "/login"
    | "/workspaces"
    | "/github/app/callback"
    | "/workspaces/$workspaceId"
    | "/workspaces/$workspaceId/projects/$projectId/schedule"
    | "/workspaces/$workspaceId/projects/$projectId/settings"
    | "/workspaces/$workspaceId/projects/$projectId"
    | "/workspaces/$workspaceId/projects/$projectId/schedule/$orchestrationId"
  id:
    | "__root__"
    | "/"
    | "/brand"
    | "/login"
    | "/workspaces"
    | "/workspaces/$workspaceId"
    | "/workspaces/"
    | "/github/app/callback"
    | "/workspaces/$workspaceId/"
    | "/workspaces/$workspaceId/projects/$projectId"
    | "/workspaces/$workspaceId/projects/$projectId/schedule"
    | "/workspaces/$workspaceId/projects/$projectId/settings"
    | "/workspaces/$workspaceId/projects/$projectId/"
    | "/workspaces/$workspaceId/projects/$projectId/schedule_/$orchestrationId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  LoginRoute: typeof LoginRoute
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  GithubAppCallbackRoute: typeof GithubAppCallbackRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workspaces": {
      id: "/workspaces"
      path: "/workspaces"
      fullPath: "/workspaces"
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/brand": {
      id: "/brand"
      path: "/brand"
      fullPath: "/brand"
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workspaces/": {
      id: "/workspaces/"
      path: "/"
      fullPath: "/workspaces/"
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    "/workspaces/$workspaceId": {
      id: "/workspaces/$workspaceId"
      path: "/$workspaceId"
      fullPath: "/workspaces/$workspaceId"
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    "/workspaces/$workspaceId/": {
      id: "/workspaces/$workspaceId/"
      path: "/"
      fullPath: "/workspaces/$workspaceId/"
      preLoaderRoute: typeof WorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRouteRoute
    }
    "/github/app/callback": {
      id: "/github/app/callback"
      path: "/github/app/callback"
      fullPath: "/github/app/callback"
      preLoaderRoute: typeof GithubAppCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workspaces/$workspaceId/projects/$projectId": {
      id: "/workspaces/$workspaceId/projects/$projectId"
      path: "/projects/$projectId"
      fullPath: "/workspaces/$workspaceId/projects/$projectId"
      preLoaderRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdRouteRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdRouteRoute
    }
    "/workspaces/$workspaceId/projects/$projectId/": {
      id: "/workspaces/$workspaceId/projects/$projectId/"
      path: "/"
      fullPath: "/workspaces/$workspaceId/projects/$projectId/"
      preLoaderRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdRouteRoute
    }
    "/workspaces/$workspaceId/projects/$projectId/settings": {
      id: "/workspaces/$workspaceId/projects/$projectId/settings"
      path: "/settings"
      fullPath: "/workspaces/$workspaceId/projects/$projectId/settings"
      preLoaderRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdSettingsRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdRouteRoute
    }
    "/workspaces/$workspaceId/projects/$projectId/schedule": {
      id: "/workspaces/$workspaceId/projects/$projectId/schedule"
      path: "/schedule"
      fullPath: "/workspaces/$workspaceId/projects/$projectId/schedule"
      preLoaderRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdScheduleRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdRouteRoute
    }
    "/workspaces/$workspaceId/projects/$projectId/schedule_/$orchestrationId": {
      id: "/workspaces/$workspaceId/projects/$projectId/schedule_/$orchestrationId"
      path: "/schedule/$orchestrationId"
      fullPath: "/workspaces/$workspaceId/projects/$projectId/schedule/$orchestrationId"
      preLoaderRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRouteImport
      parentRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdRouteRoute
    }
  }
}

interface WorkspacesWorkspaceIdProjectsProjectIdRouteRouteChildren {
  WorkspacesWorkspaceIdProjectsProjectIdScheduleRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdScheduleRoute
  WorkspacesWorkspaceIdProjectsProjectIdSettingsRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  WorkspacesWorkspaceIdProjectsProjectIdIndexRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdIndexRoute
  WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRoute
}

const WorkspacesWorkspaceIdProjectsProjectIdRouteRouteChildren: WorkspacesWorkspaceIdProjectsProjectIdRouteRouteChildren =
  {
    WorkspacesWorkspaceIdProjectsProjectIdScheduleRoute:
      WorkspacesWorkspaceIdProjectsProjectIdScheduleRoute,
    WorkspacesWorkspaceIdProjectsProjectIdSettingsRoute:
      WorkspacesWorkspaceIdProjectsProjectIdSettingsRoute,
    WorkspacesWorkspaceIdProjectsProjectIdIndexRoute:
      WorkspacesWorkspaceIdProjectsProjectIdIndexRoute,
    WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRoute:
      WorkspacesWorkspaceIdProjectsProjectIdScheduleOrchestrationIdRoute,
  }

const WorkspacesWorkspaceIdProjectsProjectIdRouteRouteWithChildren =
  WorkspacesWorkspaceIdProjectsProjectIdRouteRoute._addFileChildren(
    WorkspacesWorkspaceIdProjectsProjectIdRouteRouteChildren,
  )

interface WorkspacesWorkspaceIdRouteRouteChildren {
  WorkspacesWorkspaceIdIndexRoute: typeof WorkspacesWorkspaceIdIndexRoute
  WorkspacesWorkspaceIdProjectsProjectIdRouteRoute: typeof WorkspacesWorkspaceIdProjectsProjectIdRouteRouteWithChildren
}

const WorkspacesWorkspaceIdRouteRouteChildren: WorkspacesWorkspaceIdRouteRouteChildren =
  {
    WorkspacesWorkspaceIdIndexRoute: WorkspacesWorkspaceIdIndexRoute,
    WorkspacesWorkspaceIdProjectsProjectIdRouteRoute:
      WorkspacesWorkspaceIdProjectsProjectIdRouteRouteWithChildren,
  }

const WorkspacesWorkspaceIdRouteRouteWithChildren =
  WorkspacesWorkspaceIdRouteRoute._addFileChildren(
    WorkspacesWorkspaceIdRouteRouteChildren,
  )

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceIdRouteRoute: typeof WorkspacesWorkspaceIdRouteRouteWithChildren
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceIdRouteRoute: WorkspacesWorkspaceIdRouteRouteWithChildren,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  LoginRoute: LoginRoute,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  GithubAppCallbackRoute: GithubAppCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { startInstance } from "./start.ts"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
