export const ERROR_CODES = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",
  NOT_FOUND: "NOT_FOUND",
  CAPABILITY_CHECK_FAILED: "CAPABILITY_CHECK_FAILED",
  INVALID_PROJECT_ID: "INVALID_PROJECT_ID",
  INVALID_PROMPT: "INVALID_PROMPT",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  TASK_START_FAILED: "TASK_START_FAILED",
  INVALID_PATH: "INVALID_PATH",
  PATH_NOT_FOUND: "PATH_NOT_FOUND",
  NOT_A_DIRECTORY: "NOT_A_DIRECTORY",
  PATH_OUTSIDE_ALLOWED_ROOT: "PATH_OUTSIDE_ALLOWED_ROOT",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  READ_ERROR: "READ_ERROR",
  INVALID_CURSOR: "INVALID_CURSOR",
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
