export const ERROR_CODES = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",
  NOT_FOUND: "NOT_FOUND",
  CAPABILITY_CHECK_FAILED: "CAPABILITY_CHECK_FAILED",
  INVALID_PROJECT_ID: "INVALID_PROJECT_ID",
  INVALID_PROMPT: "INVALID_PROMPT",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  TASK_START_FAILED: "TASK_START_FAILED",
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
